defaults:
  - base_config
  - _self_
  - model: ddpm_unet
  - train: unet
  - active_learning: default
  - inference: ddpm
  - evaluation: base
  - datamodule: nanophoto
  - callbacks: default
  - trainer: default
  - experiment: null
